{
 "title": "Registration information",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "targets": [
      { "expr": "system_cpu_usage", "legendFormat": "Application" },
      { "expr": "process_cpu_usage", "legendFormat": "JVM" }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes)/1000000",
       "legendFormat": "Memory"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 7, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count[$__interval])) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Get all merchandises by supplier",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/mercadoria/fornecedor/{fornecedorId}\"}[$__interval])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/mercadoria/fornecedor/{fornecedorId}\"}[$__interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/mercadoria/fornecedor/{fornecedorId}\"}[$__interval])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Get all merchandises by warehouse",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/mercadoria/deposito/{depositoId}\"}[$__interval])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/mercadoria/deposito/{depositoId}\"}[$__interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/mercadoria/deposito/{depositoId}\"}[$__interval])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Get merchandise by id",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/mercadoria/{id}\"}[$__interval])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/mercadoria/{id}\"}[$__interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/mercadoria/{id}\"}[$__interval])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Get all customers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/cliente\"}[$__interval])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/cliente\"}[$__interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/cliente\"}[$__interval])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Get customer by id",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/cliente/{id}\"}[$__interval])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/cliente/{id}\"}[$__interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/cliente/{id}\"}[$__interval])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Get all suppliers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/fornecedor\"}[$__interval])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/fornecedor\"}[$__interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/fornecedor\"}[$__interval])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Get supplier by id",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/fornecedor/{id}\"}[$__interval])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/fornecedor/{id}\"}[$__interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/fornecedor/{id}\"}[$__interval])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Get all warehouses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/deposito\"}[$__interval])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/deposito\"}[$__interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/deposito\"}[$__interval])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Get warehouse by id",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/deposito/{id}\"}[$__interval])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/deposito/{id}\"}[$__interval])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{method=\"GET\",uri=\"/v1/deposito/{id}\"}[$__interval])) by (le))",
       "legendFormat": "p99"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true
  }
 ]
}